apiVersion: v1
kind: Secret
metadata:
  name: ordersystem-secrets
  namespace: ordersystem
type: Opaque
stringData:
  POSTGRES_USERNAME: ....
  POSTGRES_PASSWORD: ....
  RABBITMQ_USERNAME: ....
  RABBITMQ_PASSWORD: ....